version: '2.0.{build}'
skip_tags: true
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.cs'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
environment:
  COVERALLS_REPO_TOKEN:
    secure: NZsQtQe9RpYCkBOet5u2NIlhDyqgiVOels1Xfqpz2FgzEZKkrK0EvsOBSW3dUCEx
before_build:
  - nuget restore ".\query.by.specification.sln"
build:
  project: .\query.by.specification.sln
  verbosity: minimal
  publish_nuget: true
test:
  assemblies:
    - query.by.specification.IntegrationTests.dll
after_test:
  - ps: .\coveralls.ps1
deploy:
  provider: NuGet
  api_key:
    secure: Zc2Vu8QuAJHiHOwV/uo6j0rI6BuJ8xaniyjy9SdKEnWKKFo9PCJY/iSJEbItyGEF
  skip_symbols: false
  symbol_server:
  artifact: /.*\.nupkg/
notifications:
  - provider: Email
    to:
      - admin@yesmarket.com.au
      - rbartsch@adam.com.au
